openapi: 3.0.0
info:
  description: "This swagger file provides documentation for CACIB Authentication platform APIs. This documentation can be used by TPPs that want to use CACIB APIs for cash management applications."
  version: "1.0.0"
  title: "CACIB Authentication platform"
servers:
  - url: https://usignon.pre.ca-cib.com
tags:
- name: "Authentication"
  description: "CACIB Authentication platform"
  
components:
  schemas:
    TokenBody:
      type: "object"
      required:
      - "grant_type"
      - "code"
      - "client_id"
      - "redirect_uri"
      properties:
        grant_type:
          type: string
          description: "Must equal to 'authorization_code'"
        code:
          type: string
          description: "Code retrieved after the redirection from /IdPOAuth2/authorize/idp1"
        client_id:
          type: string
          description: "TPP identifier provided by the NCA (format: PSD[A-Z]{2}-[A-Z]+-.+)"
        redirect_uri:
          type: string 
          description: "TPP registered redirect_uri"
  
    TokenResponse:
      type: "object"
      properties:
        access_token:
          type: string
          description: "Access token delivered by CACIB Authentication platform"
        id_token:
          type: string
          description: "OPTIONAL - ID Token delivered by CACIB Authentication platform"
        token_type:
          type: string 
          description: "Type of the token"
        expires_in:
          type: number 
          description: "Time left before token expiration in seconds"
          
    UserinfoResponse:
      type: "object"
      properties:
        sub:
          type: string
          description: "PSU identifier"
        iss:
          type: string
          description: "Issuer of the token (CACIB Authentication platform URL)"
        active:
          type: boolean
          description: "true if the token is valid, false otherwise"
        preferred_username:
          type: string 
          description: "Username of the PSU"
        token_type:
          type: string 
          description: "Type of the token"
        given_name:
          type: string 
          description: "Given name of the PSU"
        aud:
          type: string 
          description: "Audience of the token (empty for now)"
        name:
          type: string 
          description: "PSU name"
        exp:
          type: number
          description: "Token expiration date (null for now)"
          nullable: true
        family_name:
          type: string 
          description: "PSU family name"
        iat:
          type: number
          description: "Token issuance date (null for now)"
          nullable: true
        email:
          type: string 
          description: "PSU mail"
        username:
          type: string 
          description: "PSU username"
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
    basic_auth:
      type: http
      scheme: basic

paths:
  /IdPOAuth2/authorize/idp1:
    get:
      tags:
      - "Authentication"
      summary: "CACIB platform URL for user authentication"
      description: |
        <h3>Description</h3>
          <h4>Prerequisites for all use cases</h4>
          <ul>
            <li>None</li>
          </ul>
          
          <h4>Flow</h4>
          <ul>
            <li>Before calling CACIB cash management APIs, a TPP needs to retrieve an access token from CACIB Authentication platform.</li>
            <li>The TPP redirects the PSU to /IdPOAuth2/authorize/idp1 for him to be strongly authenticated.</li>
            <li>After authentication, the PSU is redirected back to the TPP application with a code that can be later exchanged for an access token.</li>
          </ul>
      operationId: "authorize"
      parameters:
      - in: query
        name: response_type
        schema:
          type: string
        description: Must equal to 'code'
      - in: query
        name: client_id
        schema:
          type: integer
          pattern: 'PSD[A-Z]{2}-[A-Z]+-.+'
        description: TPP identifier
      - in: query
        name: redirect_uri
        schema:
          type: string
        description: TPP callback URI to which the user will be redirected after SCA (Strong Customer Authentication)
      - in: query
        name: state
        schema:
          type: string
        description: Value generated by the TPP to prevent from replay attacks
      responses:
        '302':
          description: "302 response"
          headers:
            Location:
              schema:
                type: string
              description: "<redirect_uri>?code=<authorization_code>&state=<state>"
  
  /IdPOAuth2/token/idp1:
    post:
      tags:
      - "Authentication"
      summary: "CACIB platform URL for TPP to retrieve a token"
      description: |
        <h3>Description</h3>
        
        <h4>Prerequisites for all use cases</h4>
        <ul>
          <li>The TPP has retrieved an authorization_code from CACIB Authentication platform</li>
        </ul>
        
        <h4>Flow</h4>
        <ul>
          <li>The TPP sends the authorization code alongside with its credentials to the CACIB Authentication platform</li>
          <li>The CACIB Authentication platform returns an access token with the required scope to the TPP</li>
        </ul>
      operationId: "token"
      requestBody:
        description: CACIB platform URL for TPP to retrieve a token
        required: true
        content:
         application/x-www-form-urlencoded:
          schema:
            $ref: "#/components/schemas/TokenBody"
      responses:
        '200':
          description: Authorization code exchange response
          content:
            'application/json' :
              schema:
                $ref: '#/components/schemas/TokenResponse'     
      security:
        - basic_auth: []
        
  /IdPOAuth2/userinfo/idp1:
    get:
      tags:
      - "Authentication"
      summary: "CACIB platform URL for TPP to retrieve user information"
      description: |
        <h3>Description</h3>
        
        <h4>Prerequisites for all use cases</h4>
        <ul>
          <li>The TPP has retrieved an access token from CACIB Authentication platform</li>
        </ul>
        
        <h4>Flow</h4>
        <ul>
          <li>The TPP sends the access token to the CACIB Authentication platform</li>
          <li>The CACIB Authentication platform returns the user information corresponding the the provided token</li>
        </ul>      
      operationId: "userinfo"
      responses:
        '200':
          description: Userinfo response
          content:
            'application/json' :
              schema:
                $ref: '#/components/schemas/UserinfoResponse'
      security:
        - bearer_auth: []
